version: '3'

networks:
  laravel:

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
      - mariadb
    networks:
      - laravel

  mariadb:
    platform: linux/x86_64 # Apple Chip fix
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./nginx:/etc/nginx
    environment:
      MYSQL_DATABASE: virta
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9090:9000"
    networks:
      - laravel